# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [2]:
import numpy as np
import sys

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [3]:
array_python = [0] * 1000
print(sys.getsizeof(array_python))

8056


In [4]:
array_numpy = np.zeros(1000)
print(sys.getsizeof(array_numpy))

8112


## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [46]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=np.float16)
print(array[[0, 2, -1]])

[ 0.  2. 10.]


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [50]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
print(np.sum(array[1:6]))

27.4


## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [4]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [6]:
np.mean(A, axis=0)

array([2. , 8.4])

### Task 5.2 Get the standard deviation by `y` axis

In [10]:
np.mean(A, axis=1)

array([2. , 8.4])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [5]:
np.sum(A, axis=1)

array([ 7, 10, 14, 13,  8])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [58]:
print(A[:2])

[[1 6]
 [2 8]]


##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [64]:
print(A[::2])

[[ 1  6]
 [ 3 11]
 [ 1  7]]


## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [66]:
# Python code
%time python_list = [i for i in range(1000000)]

CPU times: user 82.8 ms, sys: 57.4 ms, total: 140 ms
Wall time: 225 ms


In [67]:
%time numpy_array = np.arange(1000000)

CPU times: user 5.16 ms, sys: 8.58 ms, total: 13.7 ms
Wall time: 14 ms


### Task 6.2

In [90]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result


vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

%time unknown_signature(vector1, vector2)

CPU times: user 8 µs, sys: 1e+03 ns, total: 9 µs
Wall time: 12.9 µs


32

In [89]:
def unknown_signature(vector1, vector2):
    vector1_np = np.array(vector1)
    vector2_np = np.array(vector2)
    return np.sum(vector1_np * vector2_np)


vector1 = [1, 2, 3]
vector2 = [4, 5, 6]
%time unknown_signature(vector1, vector2)


CPU times: user 453 µs, sys: 2.72 ms, total: 3.17 ms
Wall time: 7.52 ms


32

### Task 6.3

In [87]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result


matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

%time unknown_signature(matrix1, matrix2)

CPU times: user 17 µs, sys: 1 µs, total: 18 µs
Wall time: 22.9 µs


[[5, 12], [21, 32]]

In [88]:
# Python code
def unknown_signature(matrix1, matrix2):
    matrix1_np = np.array(matrix1)
    matrix2_np = np.array(matrix2)
    return matrix1_np * matrix2_np


matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
%time unknown_signature(matrix1, matrix2)

CPU times: user 1.62 ms, sys: 6.17 ms, total: 7.79 ms
Wall time: 16 ms


array([[ 5, 12],
       [21, 32]])

### Task 6.4

In [91]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result


lst = [1, 2, 3, 4, 5]
%time unknown_signature(lst)

CPU times: user 11 µs, sys: 1 µs, total: 12 µs
Wall time: 48.9 µs


3.0

In [92]:
def unknown_signature(lst):
    lst_np = np.array(lst)
    return np.mean(lst_np)


lst = [1, 2, 3, 4, 5]
%time unknown_signature(lst)

CPU times: user 633 µs, sys: 2.49 ms, total: 3.12 ms
Wall time: 5.53 ms


3.0

## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [95]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value


lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[0, 2, 0, 4, 0]

In [98]:
def unknown_signature(lst, mask, new_value):
    lst_np = np.array(lst)
    mask_np = np.array(mask)

    lst_np[mask_np] = new_value
    return lst_np


lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
lst

[1, 2, 3, 4, 5]

### Task 7.2

In [99]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or


list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

([-6, -3, -8, -5, -10], [1, 2, 1, 0, 8], [7, 6, 7, 12, 11])

In [101]:
def unknown_signature(lst1, lst2):
    list1_np = np.array(lst1)
    lst2_np = np.array(lst2)
    bitwise_complement = ~list1_np
    bitwise_and = np.bitwise_and(list1_np, lst2_np)
    bitwise_or = np.bitwise_or(list1_np, lst2_np)
    return bitwise_complement, bitwise_and, bitwise_or


list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
result_bitwise_complement, result_bitwise_and, result_bitwise_or

(array([ -6,  -3,  -8,  -5, -10]),
 array([1, 2, 1, 0, 8]),
 array([ 7,  6,  7, 12, 11]))

### Task 7.3 Optional

In [34]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result


my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
result_python_style

[3, 13, 11, 21]

In [35]:
# write your numpy code here